

function loadHandling(v)	
	if getElementModel(v) == 562 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 2.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 5)
		setVehicleHandling(v, "maxVelocity", 350)
		setVehicleHandling(v, "engineAcceleration", 70)
		setVehicleHandling(v, "engineInertia", 80)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 402 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 2.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 270)
		setVehicleHandling(v, "engineAcceleration", 40)
		setVehicleHandling(v, "engineInertia", 40)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 436 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 2.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 250)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "engineInertia", 15)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 589 then
		setVehicleHandling(v, "mass", 1600)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 2.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 290)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 40)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 489 then
		setVehicleHandling(v, "mass", 2000)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 500)
		setVehicleHandling(v, "engineAcceleration", 50)
		setVehicleHandling(v, "engineInertia", 10)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 482 then
		setVehicleHandling(v, "mass", 2000)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 180)
		setVehicleHandling(v, "engineAcceleration", 25)
		setVehicleHandling(v, "engineInertia", 10)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 466 then
		setVehicleHandling(v, "mass", 2000)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 250)
		setVehicleHandling(v, "engineAcceleration", 15)
		setVehicleHandling(v, "engineInertia", 10)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 429 then
		setVehicleHandling(v, "mass", 2000)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 1)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 300)
		setVehicleHandling(v, "engineAcceleration", 20)
		setVehicleHandling(v, "engineInertia", 10)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 587 then
		setVehicleHandling(v, "mass", 2000)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 280)
		setVehicleHandling(v, "engineAcceleration", 30)
		setVehicleHandling(v, "engineInertia", 10)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 441 then
		setVehicleHandling(v, "mass", 2000)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 280)
		setVehicleHandling(v, "engineAcceleration", 50)
		setVehicleHandling(v, "engineInertia", 10)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
	if getElementModel(v) == 411 then
		setVehicleHandling(v, "mass", 2000)
		setVehicleHandling(v, "turnMass", 3000)
		setVehicleHandling(v, "dragCoeff", 1.5)
		setVehicleHandling(v, "centerOfMass", { 0, 0.15, -0.3 } )
		setVehicleHandling(v, "percentSubmerged", 75)
		setVehicleHandling(v, "tractionMultiplier", 0.9)
		setVehicleHandling(v, "tractionLoss", 0.9)
		setVehicleHandling(v, "tractionBias", 0.497)
		setVehicleHandling(v, "numberOfGears", 6)
		setVehicleHandling(v, "maxVelocity", 280)
		setVehicleHandling(v, "engineAcceleration", 50)
		setVehicleHandling(v, "engineInertia", 10)
		setVehicleHandling(v, "driveType", "awd")
		setVehicleHandling(v, "engineType", "petrol")
		setVehicleHandling(v, "brakeDeceleration", 50)
		setVehicleHandling(v, "ABS", false)
		setVehicleHandling(v, "steeringLock", 35)
		setVehicleHandling(v, "headLight", 0)
		setVehicleHandling(v, "tailLight", 1)
		setVehicleHandling(v, "animGroup", 0)
		setVehicleHandling(v, "suspensionUpperLimit", 0.05)
		setVehicleHandling(v, "suspensionLowerLimit", -0.06)
	end
end

function loadHandlings()
	for k, v in ipairs(getElementsByType("vehicle")) do
		loadHandling(v)
	end
end
addEventHandler("onResourceStart", getResourceRootElement(getThisResource()), loadHandlings)

function vehicleEnter()
	loadHandling(source)
end
addEventHandler("onVehicleEnter", getRootElement(), vehicleEnter)
